export const familySettingsConstants = {
  ADD_FAMILY_SETTINGS_REQUEST: 'ADD_FAMILY_SETTINGS_REQUEST',
  ADD_FAMILY_SETTINGS_SUCCESS: 'ADD_FAMILY_SETTINGS_SUCCESS',
  ADD_FAMILY_SETTINGS_FAIL: 'ADD_FAMILY_SETTINGS_FAIL',

  UPDATE_FAMILY_SETTINGS_REQUEST: 'UPDATE_FAMILY_SETTINGS_REQUEST',
  UPDATE_FAMILY_SETTINGS_SUCCESS: 'UPDATE_FAMILY_SETTINGS_SUCCESS',
  UPDATE_FAMILY_SETTINGS_FAIL: 'UPDATE_FAMILY_SETTINGS_FAIL',

  ADD_GUARDIAN_REQUEST: 'ADD_GUARDIAN_REQUEST',
  ADD_GUARDIAN_SUCCESS: 'ADD_GUARDIAN_SUCCESS',
  ADD_GUARDIAN_FAIL: 'ADD_GUARDIAN_FAIL',

  UPDATE_GUARDIAN_REQUEST: 'UPDATE_GUARDIAN_REQUEST',
  UPDATE_GUARDIAN_SUCCESS: 'UPDATE_GUARDIAN_SUCCESS',
  UPDATE_GUARDIAN_FAIL: 'UPDATE_GUARDIAN_FAIL',

  DELETE_GUARDIAN_REQUEST: 'DELETE_GUARDIAN_REQUEST',
  DELETE_GUARDIAN_SUCCESS: 'DELETE_GUARDIAN_SUCCESS',
  DELETE_GUARDIAN_FAIL: 'DELETE_GUARDIAN_FAIL',

  ADD_CHILD_REQUEST: 'ADD_CHILD_REQUEST',
  ADD_CHILD_SUCCESS: 'ADD_CHILD_SUCCESS',
  ADD_CHILD_FAIL: 'ADD_CHILD_FAIL',

  UPDATE_CHILD_REQUEST: 'UPDATE_CHILD_REQUEST',
  UPDATE_CHILD_SUCCESS: 'UPDATE_CHILD_SUCCESS',
  UPDATE_CHILD_FAIL: 'UPDATE_CHILD_FAIL',

  DELETE_CHILD_REQUEST: 'DELETE_CHILD_REQUEST',
  DELETE_CHILD_SUCCESS: 'DELETE_CHILD_SUCCESS',
  DELETE_CHILD_FAIL: 'DELETE_CHILD_FAIL',

  GET_CHILDREN_REQUEST: 'GET_CHILDREN_REQUEST',
  GET_CHILDREN_SUCCESS: 'GET_CHILDREN_SUCCESS',
  GET_CHILDREN_FAIL: 'GET_CHILDREN_FAIL',
};
