export const matricsConstants = {
  ADD_MATRIC_REQUEST: 'ADD_MATRIC_REQUEST',
  ADD_MATRIC_SUCCESS: 'ADD_MATRIC_SUCCESS',
  ADD_MATRIC_FAIL: 'ADD_MATRIC_FAIL',
  GET_MATRICS_REQUEST: 'GET_MATRICS_REQUEST',
  GET_MATRICS_SUCCESS: 'GET_MATRICS_SUCCESS',
  GET_MATRICS_FAIL: 'GET_MATRICS_FAIL',
  UPDATE_MATRICS_REQUEST: 'UPDATE_MATRICS_REQUEST',
  UPDATE_MATRICS_SUCCESS: 'UPDATE_MATRICS_SUCCESS',
  UPDATE_MATRICS_FAIL: 'UPDATE_MATRICS_FAIL',
};
