export const subMatricsConstants = {
  ADD_SUB_MATRIC_REQUEST: 'ADD_SUB_MATRIC_REQUEST',
  ADD_SUB_MATRIC_SUCCESS: 'ADD_SUB_MATRIC_SUCCESS',
  ADD_SUB_MATRIC_FAIL: 'ADD_SUB_MATRIC_FAIL',

  EDIT_SUB_MATRIC_REQUEST: 'EDIT_SUB_MATRIC_REQUEST',
  EDIT_SUB_MATRIC_SUCCESS: 'EDIT_SUB_MATRIC_SUCCESS',
  EDIT_SUB_MATRIC_FAIL: 'EDIT_SUB_MATRIC_FAIL',

  GET_SUB_MATRICS_REQUEST: 'GET_SUB_MATRICS_REQUEST',
  GET_SUB_MATRICS_SUCCESS: 'GET_SUB_MATRICS_SUCCESS',
  GET_SUB_MATRICS_FAIL: 'GET_SUB_MATRICS_FAIL',

  UPDATE_SUB_MATRICS_REQUEST: 'UPDATE_SUB_MATRICS_REQUEST',
  UPDATE_SUB_MATRICS_SUCCESS: 'UPDATE_SUB_MATRICS_SUCCESS',
  UPDATE_SUB_MATRICS_FAIL: 'UPDATE_SUB_MATRICS_FAIL',

  DELETE_SUB_MATRIC_REQUEST: 'DELETE_SUB_MATRIC_REQUEST',
  DELETE_SUB_MATRIC_SUCCESS: 'DELETE_SUB_MATRIC_SUCCESS',
  DELETE_SUB_MATRIC_FAIL: 'DELETE_SUB_MATRIC_FAIL',

  ASSIGN_TASK_REQUEST: 'ASSIGN_TASK_REQUEST',
  ASSIGN_TASK_SUCCESS: 'ASSIGN_TASK_SUCCESS',
  ASSIGN_TASK_FAIL: 'ASSIGN_TASK_FAIL',
};
