export enum AppRoute {
  AUTH = 'Auth',
  AUTH_WELCOME = 'Welcome',
  DASHBOARD = 'Dashboard',
  MATRIC_CATEGORY = 'Matric Category',
  MATRIC_SUB_CATEGORY = 'Matric Sub Category',
  PARENT_PROFILE = 'Parent Profile',
  CHILD_PROFILE = 'Child Profile',
  FAMILY_SETUP = 'Family Setup',
  ADD_PARENT = 'Add Parent',
  ADD_CHILD = 'Add Child',
  ONBOARDING = 'Onboarding',
  SIGN_IN = 'Sign In',
  SIGN_UP = 'Sign Up',
  RESET_PASSWORD = 'Reset Passrord',
  HOME = 'Home',
  SETTINGS = 'Settings',
  PAGES = 'pages',
  PROFILE = 'Profile',
  ABOUT = 'About',
  ASSIGN_TASK = 'Assign Task',
}
